#!/bin/sh

OS="macxxx"
#OS="linux"

fullName="$1" 
fullPath="$2"
fileName="$3"

SP="${fullPath}"
SP1="${fullPath}"

#echo "basename $SP"
fileTxt="${fullName}.txt"
fileJ="${fullName}.j"
logOut="${fullName}.out"
classFile="${fullName}.class"

jar1="${fullPath}TestScript.jar"
jarTestScript="TestScript.jar"
jar2="${fullPath}jasmin.jar"

echo "trying to compile..." > "${logOut}"


(java -jar "${jar1}" "$fileTxt" >> "${logOut}") & pid=$!
( sleep 2 && kill -HUP $pid ) 2>/dev/null & watcher=$!
if wait $pid 2>/dev/null; then
    #echo "your_command finished"
    pkill -HUP -P $watcher
    wait $watcher

    if [ -f $logOut ]
    then
        echo "Test Script compiler successfully compiled txt" >> "${logOut}"
    else
        echo "compiler Error could not parse file" >> ${logOut}
    fi
else
    #echo "command interrupted"
    echo "Test Script compilation failed due to timeout" >> ${logOut}
fi

# compile the jasmine files 
echo "compiling jasmine file to .class file" >> ${logOut}
echo "java -jar jasmin.jar ${fileName}.j" >> ${logOut}

#if [ $OS=="mac" ] 
#    then
#        java -jar $jar2 "${fileJ}" -d "../test_script"
#    else
        java -jar $jar2 "${fileJ}" -d "./test_script"
#fi

# run the class files 
echo "file location for class file ${fileName}.class" >> ${logOut} 
if [ -f $classFile ]
    then
        echo "running the class file on JVM" >> ${logOut}
        echo "java -cp ${fullName} ${fullName}"  >> ${logOut}
        echo '----------- Code Execution -----------' >> ${logOut}
        java  -cp "${fullPath}" "${fileName}" >> ${logOut}
    else
        echo "jasmin code generation error: .class file could not be generated" >> ${logOut}
        echo "terminating compilation..." >> ${logOut}
fi

